/* tslint:disable */
/* eslint-disable */
//  This file was automatically generated and should not be edited.

export type CreateQuestionInput = {
  id?: string | null,
  questionType: QuestionType,
  titleEnglish: string,
  titleChinese: string,
  contentEnglish?: string | null,
  contentChinese?: string | null,
  _version?: number | null,
};

export enum QuestionType {
  ID = "ID",
  TEXT = "TEXT",
  BOOLEAN = "BOOLEAN",
  SINGLESELECT = "SINGLESELECT",
  MULTISELECT = "MULTISELECT",
  SIGNATURE = "SIGNATURE",
}


export type ModelQuestionConditionInput = {
  questionType?: ModelQuestionTypeInput | null,
  titleEnglish?: ModelStringInput | null,
  titleChinese?: ModelStringInput | null,
  contentEnglish?: ModelStringInput | null,
  contentChinese?: ModelStringInput | null,
  and?: Array< ModelQuestionConditionInput | null > | null,
  or?: Array< ModelQuestionConditionInput | null > | null,
  not?: ModelQuestionConditionInput | null,
};

export type ModelQuestionTypeInput = {
  eq?: QuestionType | null,
  ne?: QuestionType | null,
};

export type ModelStringInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export enum ModelAttributeTypes {
  binary = "binary",
  binarySet = "binarySet",
  bool = "bool",
  list = "list",
  map = "map",
  number = "number",
  numberSet = "numberSet",
  string = "string",
  stringSet = "stringSet",
  _null = "_null",
}


export type ModelSizeInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
};

export type Question = {
  __typename: "Question",
  id?: string,
  questionType?: QuestionType,
  titleEnglish?: string,
  titleChinese?: string,
  contentEnglish?: string | null,
  contentChinese?: string | null,
  _version?: number,
  _deleted?: boolean | null,
  _lastChangedAt?: number,
  createdAt?: string,
  updatedAt?: string,
};

export type UpdateQuestionInput = {
  id: string,
  questionType?: QuestionType | null,
  titleEnglish?: string | null,
  titleChinese?: string | null,
  contentEnglish?: string | null,
  contentChinese?: string | null,
  _version?: number | null,
};

export type DeleteQuestionInput = {
  id?: string | null,
  _version?: number | null,
};

export type CreateSubmissionInput = {
  id?: string | null,
  submissionType: SubmissionType,
  submittedAt: string,
  temperature?: number | null,
  conditionsMet: boolean,
  signature: boolean,
  division?: Division | null,
  firstName: string,
  lastName: string,
  phone: string,
  parentID?: string | null,
  parentName?: string | null,
  parentPhone?: string | null,
  personID: string,
  familyID?: string | null,
  consultantType?: ConsultantType | null,
  _version?: number | null,
};

export enum SubmissionType {
  STUDENT = "STUDENT",
  EMPLOYEE = "EMPLOYEE",
  VISITOR = "VISITOR",
  CONSULTANT = "CONSULTANT",
}


export enum Division {
  EC = "EC",
  ES = "ES",
  MS = "MS",
  HS = "HS",
  ALLSCHOOL = "ALLSCHOOL",
}


export enum ConsultantType {
  CONTRACTOR = "CONTRACTOR",
  SCHOOLBUSDRIVER = "SCHOOLBUSDRIVER",
  SCHOOLBUSMONITOR = "SCHOOLBUSMONITOR",
  SUBSTITUTETEACHER = "SUBSTITUTETEACHER",
  CONSULTANT = "CONSULTANT",
  CCAINSTRUCTOR = "CCAINSTRUCTOR",
}


export type ModelSubmissionConditionInput = {
  submissionType?: ModelSubmissionTypeInput | null,
  submittedAt?: ModelStringInput | null,
  temperature?: ModelFloatInput | null,
  conditionsMet?: ModelBooleanInput | null,
  signature?: ModelBooleanInput | null,
  division?: ModelDivisionInput | null,
  firstName?: ModelStringInput | null,
  lastName?: ModelStringInput | null,
  phone?: ModelStringInput | null,
  parentID?: ModelIDInput | null,
  parentName?: ModelStringInput | null,
  parentPhone?: ModelStringInput | null,
  personID?: ModelIDInput | null,
  familyID?: ModelIDInput | null,
  consultantType?: ModelConsultantTypeInput | null,
  and?: Array< ModelSubmissionConditionInput | null > | null,
  or?: Array< ModelSubmissionConditionInput | null > | null,
  not?: ModelSubmissionConditionInput | null,
};

export type ModelSubmissionTypeInput = {
  eq?: SubmissionType | null,
  ne?: SubmissionType | null,
};

export type ModelFloatInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
};

export type ModelBooleanInput = {
  ne?: boolean | null,
  eq?: boolean | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
};

export type ModelDivisionInput = {
  eq?: Division | null,
  ne?: Division | null,
};

export type ModelIDInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export type ModelConsultantTypeInput = {
  eq?: ConsultantType | null,
  ne?: ConsultantType | null,
};

export type Submission = {
  __typename: "Submission",
  id?: string,
  submissionType?: SubmissionType,
  submittedAt?: string,
  temperature?: number | null,
  conditionsMet?: boolean,
  signature?: boolean,
  division?: Division | null,
  firstName?: string,
  lastName?: string,
  phone?: string,
  parentID?: string | null,
  parentName?: string | null,
  parentPhone?: string | null,
  personID?: string,
  familyID?: string | null,
  consultantType?: ConsultantType | null,
  _version?: number,
  _deleted?: boolean | null,
  _lastChangedAt?: number,
  createdAt?: string,
  updatedAt?: string,
};

export type UpdateSubmissionInput = {
  id: string,
  submissionType?: SubmissionType | null,
  submittedAt?: string | null,
  temperature?: number | null,
  conditionsMet?: boolean | null,
  signature?: boolean | null,
  division?: Division | null,
  firstName?: string | null,
  lastName?: string | null,
  phone?: string | null,
  parentID?: string | null,
  parentName?: string | null,
  parentPhone?: string | null,
  personID?: string | null,
  familyID?: string | null,
  consultantType?: ConsultantType | null,
  _version?: number | null,
};

export type DeleteSubmissionInput = {
  id?: string | null,
  _version?: number | null,
};

export type CreateFamilyInput = {
  id?: string | null,
  createdAt?: string | null,
  updatedAt?: string | null,
  _version?: number | null,
};

export type ModelFamilyConditionInput = {
  createdAt?: ModelStringInput | null,
  updatedAt?: ModelStringInput | null,
  and?: Array< ModelFamilyConditionInput | null > | null,
  or?: Array< ModelFamilyConditionInput | null > | null,
  not?: ModelFamilyConditionInput | null,
};

export type Family = {
  __typename: "Family",
  id?: string,
  createdAt?: string,
  updatedAt?: string,
  _version?: number,
  _deleted?: boolean | null,
  _lastChangedAt?: number,
  submissions?: ModelSubmissionConnection,
  members?: ModelPersonConnection,
};

export type ModelSubmissionConnection = {
  __typename: "ModelSubmissionConnection",
  items?:  Array<Submission | null > | null,
  nextToken?: string | null,
  startedAt?: number | null,
};

export type ModelPersonConnection = {
  __typename: "ModelPersonConnection",
  items?:  Array<Person | null > | null,
  nextToken?: string | null,
  startedAt?: number | null,
};

export type Person = {
  __typename: "Person",
  id?: string,
  firstName?: string,
  lastName?: string,
  phone?: string | null,
  email?: string | null,
  division?: Division | null,
  fatherPhone?: string | null,
  motherPhone?: string | null,
  fatherEmail?: string | null,
  motherEmail?: string | null,
  createdAt?: string,
  updatedAt?: string,
  submissionType?: SubmissionType,
  isAuthenticatedUser?: boolean,
  familyMemberType?: FamilyMemberType | null,
  familyID?: string | null,
  consultantType?: ConsultantType | null,
  governmentID?: string | null,
  _version?: number,
  _deleted?: boolean | null,
  _lastChangedAt?: number,
  submissions?: ModelSubmissionConnection,
};

export enum FamilyMemberType {
  PARENT = "PARENT",
  CHILD = "CHILD",
}


export type UpdateFamilyInput = {
  id: string,
  createdAt?: string | null,
  updatedAt?: string | null,
  _version?: number | null,
};

export type DeleteFamilyInput = {
  id?: string | null,
  _version?: number | null,
};

export type CreatePersonInput = {
  id?: string | null,
  firstName: string,
  lastName: string,
  phone?: string | null,
  email?: string | null,
  division?: Division | null,
  fatherPhone?: string | null,
  motherPhone?: string | null,
  fatherEmail?: string | null,
  motherEmail?: string | null,
  createdAt?: string | null,
  updatedAt?: string | null,
  submissionType: SubmissionType,
  isAuthenticatedUser: boolean,
  familyMemberType?: FamilyMemberType | null,
  familyID?: string | null,
  consultantType?: ConsultantType | null,
  governmentID?: string | null,
  _version?: number | null,
};

export type ModelPersonConditionInput = {
  firstName?: ModelStringInput | null,
  lastName?: ModelStringInput | null,
  phone?: ModelStringInput | null,
  email?: ModelStringInput | null,
  division?: ModelDivisionInput | null,
  fatherPhone?: ModelStringInput | null,
  motherPhone?: ModelStringInput | null,
  fatherEmail?: ModelStringInput | null,
  motherEmail?: ModelStringInput | null,
  createdAt?: ModelStringInput | null,
  updatedAt?: ModelStringInput | null,
  submissionType?: ModelSubmissionTypeInput | null,
  isAuthenticatedUser?: ModelBooleanInput | null,
  familyMemberType?: ModelFamilyMemberTypeInput | null,
  familyID?: ModelIDInput | null,
  consultantType?: ModelConsultantTypeInput | null,
  governmentID?: ModelStringInput | null,
  and?: Array< ModelPersonConditionInput | null > | null,
  or?: Array< ModelPersonConditionInput | null > | null,
  not?: ModelPersonConditionInput | null,
};

export type ModelFamilyMemberTypeInput = {
  eq?: FamilyMemberType | null,
  ne?: FamilyMemberType | null,
};

export type UpdatePersonInput = {
  id: string,
  firstName?: string | null,
  lastName?: string | null,
  phone?: string | null,
  email?: string | null,
  division?: Division | null,
  fatherPhone?: string | null,
  motherPhone?: string | null,
  fatherEmail?: string | null,
  motherEmail?: string | null,
  createdAt?: string | null,
  updatedAt?: string | null,
  submissionType?: SubmissionType | null,
  isAuthenticatedUser?: boolean | null,
  familyMemberType?: FamilyMemberType | null,
  familyID?: string | null,
  consultantType?: ConsultantType | null,
  governmentID?: string | null,
  _version?: number | null,
};

export type DeletePersonInput = {
  id?: string | null,
  _version?: number | null,
};

export type ModelQuestionFilterInput = {
  id?: ModelIDInput | null,
  questionType?: ModelQuestionTypeInput | null,
  titleEnglish?: ModelStringInput | null,
  titleChinese?: ModelStringInput | null,
  contentEnglish?: ModelStringInput | null,
  contentChinese?: ModelStringInput | null,
  and?: Array< ModelQuestionFilterInput | null > | null,
  or?: Array< ModelQuestionFilterInput | null > | null,
  not?: ModelQuestionFilterInput | null,
};

export type ModelQuestionConnection = {
  __typename: "ModelQuestionConnection",
  items?:  Array<Question | null > | null,
  nextToken?: string | null,
  startedAt?: number | null,
};

export type ModelSubmissionFilterInput = {
  id?: ModelIDInput | null,
  submissionType?: ModelSubmissionTypeInput | null,
  submittedAt?: ModelStringInput | null,
  temperature?: ModelFloatInput | null,
  conditionsMet?: ModelBooleanInput | null,
  signature?: ModelBooleanInput | null,
  division?: ModelDivisionInput | null,
  firstName?: ModelStringInput | null,
  lastName?: ModelStringInput | null,
  phone?: ModelStringInput | null,
  parentID?: ModelIDInput | null,
  parentName?: ModelStringInput | null,
  parentPhone?: ModelStringInput | null,
  personID?: ModelIDInput | null,
  familyID?: ModelIDInput | null,
  consultantType?: ModelConsultantTypeInput | null,
  and?: Array< ModelSubmissionFilterInput | null > | null,
  or?: Array< ModelSubmissionFilterInput | null > | null,
  not?: ModelSubmissionFilterInput | null,
};

export type ModelFamilyFilterInput = {
  id?: ModelIDInput | null,
  createdAt?: ModelStringInput | null,
  updatedAt?: ModelStringInput | null,
  and?: Array< ModelFamilyFilterInput | null > | null,
  or?: Array< ModelFamilyFilterInput | null > | null,
  not?: ModelFamilyFilterInput | null,
};

export type ModelFamilyConnection = {
  __typename: "ModelFamilyConnection",
  items?:  Array<Family | null > | null,
  nextToken?: string | null,
  startedAt?: number | null,
};

export type ModelPersonFilterInput = {
  id?: ModelIDInput | null,
  firstName?: ModelStringInput | null,
  lastName?: ModelStringInput | null,
  phone?: ModelStringInput | null,
  email?: ModelStringInput | null,
  division?: ModelDivisionInput | null,
  fatherPhone?: ModelStringInput | null,
  motherPhone?: ModelStringInput | null,
  fatherEmail?: ModelStringInput | null,
  motherEmail?: ModelStringInput | null,
  createdAt?: ModelStringInput | null,
  updatedAt?: ModelStringInput | null,
  submissionType?: ModelSubmissionTypeInput | null,
  isAuthenticatedUser?: ModelBooleanInput | null,
  familyMemberType?: ModelFamilyMemberTypeInput | null,
  familyID?: ModelIDInput | null,
  consultantType?: ModelConsultantTypeInput | null,
  governmentID?: ModelStringInput | null,
  and?: Array< ModelPersonFilterInput | null > | null,
  or?: Array< ModelPersonFilterInput | null > | null,
  not?: ModelPersonFilterInput | null,
};

export type CreateQuestionMutationVariables = {
  input?: CreateQuestionInput,
  condition?: ModelQuestionConditionInput | null,
};

export type CreateQuestionMutation = {
  createQuestion?:  {
    __typename: "Question",
    id: string,
    questionType: QuestionType,
    titleEnglish: string,
    titleChinese: string,
    contentEnglish?: string | null,
    contentChinese?: string | null,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type UpdateQuestionMutationVariables = {
  input?: UpdateQuestionInput,
  condition?: ModelQuestionConditionInput | null,
};

export type UpdateQuestionMutation = {
  updateQuestion?:  {
    __typename: "Question",
    id: string,
    questionType: QuestionType,
    titleEnglish: string,
    titleChinese: string,
    contentEnglish?: string | null,
    contentChinese?: string | null,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type DeleteQuestionMutationVariables = {
  input?: DeleteQuestionInput,
  condition?: ModelQuestionConditionInput | null,
};

export type DeleteQuestionMutation = {
  deleteQuestion?:  {
    __typename: "Question",
    id: string,
    questionType: QuestionType,
    titleEnglish: string,
    titleChinese: string,
    contentEnglish?: string | null,
    contentChinese?: string | null,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type CreateSubmissionMutationVariables = {
  input?: CreateSubmissionInput,
  condition?: ModelSubmissionConditionInput | null,
};

export type CreateSubmissionMutation = {
  createSubmission?:  {
    __typename: "Submission",
    id: string,
    submissionType: SubmissionType,
    submittedAt: string,
    temperature?: number | null,
    conditionsMet: boolean,
    signature: boolean,
    division?: Division | null,
    firstName: string,
    lastName: string,
    phone: string,
    parentID?: string | null,
    parentName?: string | null,
    parentPhone?: string | null,
    personID: string,
    familyID?: string | null,
    consultantType?: ConsultantType | null,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type UpdateSubmissionMutationVariables = {
  input?: UpdateSubmissionInput,
  condition?: ModelSubmissionConditionInput | null,
};

export type UpdateSubmissionMutation = {
  updateSubmission?:  {
    __typename: "Submission",
    id: string,
    submissionType: SubmissionType,
    submittedAt: string,
    temperature?: number | null,
    conditionsMet: boolean,
    signature: boolean,
    division?: Division | null,
    firstName: string,
    lastName: string,
    phone: string,
    parentID?: string | null,
    parentName?: string | null,
    parentPhone?: string | null,
    personID: string,
    familyID?: string | null,
    consultantType?: ConsultantType | null,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type DeleteSubmissionMutationVariables = {
  input?: DeleteSubmissionInput,
  condition?: ModelSubmissionConditionInput | null,
};

export type DeleteSubmissionMutation = {
  deleteSubmission?:  {
    __typename: "Submission",
    id: string,
    submissionType: SubmissionType,
    submittedAt: string,
    temperature?: number | null,
    conditionsMet: boolean,
    signature: boolean,
    division?: Division | null,
    firstName: string,
    lastName: string,
    phone: string,
    parentID?: string | null,
    parentName?: string | null,
    parentPhone?: string | null,
    personID: string,
    familyID?: string | null,
    consultantType?: ConsultantType | null,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type CreateFamilyMutationVariables = {
  input?: CreateFamilyInput,
  condition?: ModelFamilyConditionInput | null,
};

export type CreateFamilyMutation = {
  createFamily?:  {
    __typename: "Family",
    id: string,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
    submissions?:  {
      __typename: "ModelSubmissionConnection",
      items?:  Array< {
        __typename: "Submission",
        id: string,
        submissionType: SubmissionType,
        submittedAt: string,
        temperature?: number | null,
        conditionsMet: boolean,
        signature: boolean,
        division?: Division | null,
        firstName: string,
        lastName: string,
        phone: string,
        parentID?: string | null,
        parentName?: string | null,
        parentPhone?: string | null,
        personID: string,
        familyID?: string | null,
        consultantType?: ConsultantType | null,
        _version: number,
        _deleted?: boolean | null,
        _lastChangedAt: number,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      nextToken?: string | null,
      startedAt?: number | null,
    } | null,
    members?:  {
      __typename: "ModelPersonConnection",
      items?:  Array< {
        __typename: "Person",
        id: string,
        firstName: string,
        lastName: string,
        phone?: string | null,
        email?: string | null,
        division?: Division | null,
        fatherPhone?: string | null,
        motherPhone?: string | null,
        fatherEmail?: string | null,
        motherEmail?: string | null,
        createdAt: string,
        updatedAt: string,
        submissionType: SubmissionType,
        isAuthenticatedUser: boolean,
        familyMemberType?: FamilyMemberType | null,
        familyID?: string | null,
        consultantType?: ConsultantType | null,
        governmentID?: string | null,
        _version: number,
        _deleted?: boolean | null,
        _lastChangedAt: number,
        submissions?:  {
          __typename: "ModelSubmissionConnection",
          items?:  Array< {
            __typename: "Submission",
            id: string,
            submissionType: SubmissionType,
            submittedAt: string,
            temperature?: number | null,
            conditionsMet: boolean,
            signature: boolean,
            division?: Division | null,
            firstName: string,
            lastName: string,
            phone: string,
            parentID?: string | null,
            parentName?: string | null,
            parentPhone?: string | null,
            personID: string,
            familyID?: string | null,
            consultantType?: ConsultantType | null,
            _version: number,
            _deleted?: boolean | null,
            _lastChangedAt: number,
            createdAt: string,
            updatedAt: string,
          } | null > | null,
          nextToken?: string | null,
          startedAt?: number | null,
        } | null,
      } | null > | null,
      nextToken?: string | null,
      startedAt?: number | null,
    } | null,
  } | null,
};

export type UpdateFamilyMutationVariables = {
  input?: UpdateFamilyInput,
  condition?: ModelFamilyConditionInput | null,
};

export type UpdateFamilyMutation = {
  updateFamily?:  {
    __typename: "Family",
    id: string,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
    submissions?:  {
      __typename: "ModelSubmissionConnection",
      items?:  Array< {
        __typename: "Submission",
        id: string,
        submissionType: SubmissionType,
        submittedAt: string,
        temperature?: number | null,
        conditionsMet: boolean,
        signature: boolean,
        division?: Division | null,
        firstName: string,
        lastName: string,
        phone: string,
        parentID?: string | null,
        parentName?: string | null,
        parentPhone?: string | null,
        personID: string,
        familyID?: string | null,
        consultantType?: ConsultantType | null,
        _version: number,
        _deleted?: boolean | null,
        _lastChangedAt: number,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      nextToken?: string | null,
      startedAt?: number | null,
    } | null,
    members?:  {
      __typename: "ModelPersonConnection",
      items?:  Array< {
        __typename: "Person",
        id: string,
        firstName: string,
        lastName: string,
        phone?: string | null,
        email?: string | null,
        division?: Division | null,
        fatherPhone?: string | null,
        motherPhone?: string | null,
        fatherEmail?: string | null,
        motherEmail?: string | null,
        createdAt: string,
        updatedAt: string,
        submissionType: SubmissionType,
        isAuthenticatedUser: boolean,
        familyMemberType?: FamilyMemberType | null,
        familyID?: string | null,
        consultantType?: ConsultantType | null,
        governmentID?: string | null,
        _version: number,
        _deleted?: boolean | null,
        _lastChangedAt: number,
        submissions?:  {
          __typename: "ModelSubmissionConnection",
          items?:  Array< {
            __typename: "Submission",
            id: string,
            submissionType: SubmissionType,
            submittedAt: string,
            temperature?: number | null,
            conditionsMet: boolean,
            signature: boolean,
            division?: Division | null,
            firstName: string,
            lastName: string,
            phone: string,
            parentID?: string | null,
            parentName?: string | null,
            parentPhone?: string | null,
            personID: string,
            familyID?: string | null,
            consultantType?: ConsultantType | null,
            _version: number,
            _deleted?: boolean | null,
            _lastChangedAt: number,
            createdAt: string,
            updatedAt: string,
          } | null > | null,
          nextToken?: string | null,
          startedAt?: number | null,
        } | null,
      } | null > | null,
      nextToken?: string | null,
      startedAt?: number | null,
    } | null,
  } | null,
};

export type DeleteFamilyMutationVariables = {
  input?: DeleteFamilyInput,
  condition?: ModelFamilyConditionInput | null,
};

export type DeleteFamilyMutation = {
  deleteFamily?:  {
    __typename: "Family",
    id: string,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
    submissions?:  {
      __typename: "ModelSubmissionConnection",
      items?:  Array< {
        __typename: "Submission",
        id: string,
        submissionType: SubmissionType,
        submittedAt: string,
        temperature?: number | null,
        conditionsMet: boolean,
        signature: boolean,
        division?: Division | null,
        firstName: string,
        lastName: string,
        phone: string,
        parentID?: string | null,
        parentName?: string | null,
        parentPhone?: string | null,
        personID: string,
        familyID?: string | null,
        consultantType?: ConsultantType | null,
        _version: number,
        _deleted?: boolean | null,
        _lastChangedAt: number,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      nextToken?: string | null,
      startedAt?: number | null,
    } | null,
    members?:  {
      __typename: "ModelPersonConnection",
      items?:  Array< {
        __typename: "Person",
        id: string,
        firstName: string,
        lastName: string,
        phone?: string | null,
        email?: string | null,
        division?: Division | null,
        fatherPhone?: string | null,
        motherPhone?: string | null,
        fatherEmail?: string | null,
        motherEmail?: string | null,
        createdAt: string,
        updatedAt: string,
        submissionType: SubmissionType,
        isAuthenticatedUser: boolean,
        familyMemberType?: FamilyMemberType | null,
        familyID?: string | null,
        consultantType?: ConsultantType | null,
        governmentID?: string | null,
        _version: number,
        _deleted?: boolean | null,
        _lastChangedAt: number,
        submissions?:  {
          __typename: "ModelSubmissionConnection",
          items?:  Array< {
            __typename: "Submission",
            id: string,
            submissionType: SubmissionType,
            submittedAt: string,
            temperature?: number | null,
            conditionsMet: boolean,
            signature: boolean,
            division?: Division | null,
            firstName: string,
            lastName: string,
            phone: string,
            parentID?: string | null,
            parentName?: string | null,
            parentPhone?: string | null,
            personID: string,
            familyID?: string | null,
            consultantType?: ConsultantType | null,
            _version: number,
            _deleted?: boolean | null,
            _lastChangedAt: number,
            createdAt: string,
            updatedAt: string,
          } | null > | null,
          nextToken?: string | null,
          startedAt?: number | null,
        } | null,
      } | null > | null,
      nextToken?: string | null,
      startedAt?: number | null,
    } | null,
  } | null,
};

export type CreatePersonMutationVariables = {
  input?: CreatePersonInput,
  condition?: ModelPersonConditionInput | null,
};

export type CreatePersonMutation = {
  createPerson?:  {
    __typename: "Person",
    id: string,
    firstName: string,
    lastName: string,
    phone?: string | null,
    email?: string | null,
    division?: Division | null,
    fatherPhone?: string | null,
    motherPhone?: string | null,
    fatherEmail?: string | null,
    motherEmail?: string | null,
    createdAt: string,
    updatedAt: string,
    submissionType: SubmissionType,
    isAuthenticatedUser: boolean,
    familyMemberType?: FamilyMemberType | null,
    familyID?: string | null,
    consultantType?: ConsultantType | null,
    governmentID?: string | null,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
    submissions?:  {
      __typename: "ModelSubmissionConnection",
      items?:  Array< {
        __typename: "Submission",
        id: string,
        submissionType: SubmissionType,
        submittedAt: string,
        temperature?: number | null,
        conditionsMet: boolean,
        signature: boolean,
        division?: Division | null,
        firstName: string,
        lastName: string,
        phone: string,
        parentID?: string | null,
        parentName?: string | null,
        parentPhone?: string | null,
        personID: string,
        familyID?: string | null,
        consultantType?: ConsultantType | null,
        _version: number,
        _deleted?: boolean | null,
        _lastChangedAt: number,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      nextToken?: string | null,
      startedAt?: number | null,
    } | null,
  } | null,
};

export type UpdatePersonMutationVariables = {
  input?: UpdatePersonInput,
  condition?: ModelPersonConditionInput | null,
};

export type UpdatePersonMutation = {
  updatePerson?:  {
    __typename: "Person",
    id: string,
    firstName: string,
    lastName: string,
    phone?: string | null,
    email?: string | null,
    division?: Division | null,
    fatherPhone?: string | null,
    motherPhone?: string | null,
    fatherEmail?: string | null,
    motherEmail?: string | null,
    createdAt: string,
    updatedAt: string,
    submissionType: SubmissionType,
    isAuthenticatedUser: boolean,
    familyMemberType?: FamilyMemberType | null,
    familyID?: string | null,
    consultantType?: ConsultantType | null,
    governmentID?: string | null,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
    submissions?:  {
      __typename: "ModelSubmissionConnection",
      items?:  Array< {
        __typename: "Submission",
        id: string,
        submissionType: SubmissionType,
        submittedAt: string,
        temperature?: number | null,
        conditionsMet: boolean,
        signature: boolean,
        division?: Division | null,
        firstName: string,
        lastName: string,
        phone: string,
        parentID?: string | null,
        parentName?: string | null,
        parentPhone?: string | null,
        personID: string,
        familyID?: string | null,
        consultantType?: ConsultantType | null,
        _version: number,
        _deleted?: boolean | null,
        _lastChangedAt: number,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      nextToken?: string | null,
      startedAt?: number | null,
    } | null,
  } | null,
};

export type DeletePersonMutationVariables = {
  input?: DeletePersonInput,
  condition?: ModelPersonConditionInput | null,
};

export type DeletePersonMutation = {
  deletePerson?:  {
    __typename: "Person",
    id: string,
    firstName: string,
    lastName: string,
    phone?: string | null,
    email?: string | null,
    division?: Division | null,
    fatherPhone?: string | null,
    motherPhone?: string | null,
    fatherEmail?: string | null,
    motherEmail?: string | null,
    createdAt: string,
    updatedAt: string,
    submissionType: SubmissionType,
    isAuthenticatedUser: boolean,
    familyMemberType?: FamilyMemberType | null,
    familyID?: string | null,
    consultantType?: ConsultantType | null,
    governmentID?: string | null,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
    submissions?:  {
      __typename: "ModelSubmissionConnection",
      items?:  Array< {
        __typename: "Submission",
        id: string,
        submissionType: SubmissionType,
        submittedAt: string,
        temperature?: number | null,
        conditionsMet: boolean,
        signature: boolean,
        division?: Division | null,
        firstName: string,
        lastName: string,
        phone: string,
        parentID?: string | null,
        parentName?: string | null,
        parentPhone?: string | null,
        personID: string,
        familyID?: string | null,
        consultantType?: ConsultantType | null,
        _version: number,
        _deleted?: boolean | null,
        _lastChangedAt: number,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      nextToken?: string | null,
      startedAt?: number | null,
    } | null,
  } | null,
};

export type GetQuestionQueryVariables = {
  id?: string,
};

export type GetQuestionQuery = {
  getQuestion?:  {
    __typename: "Question",
    id: string,
    questionType: QuestionType,
    titleEnglish: string,
    titleChinese: string,
    contentEnglish?: string | null,
    contentChinese?: string | null,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type ListQuestionsQueryVariables = {
  filter?: ModelQuestionFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListQuestionsQuery = {
  listQuestions?:  {
    __typename: "ModelQuestionConnection",
    items?:  Array< {
      __typename: "Question",
      id: string,
      questionType: QuestionType,
      titleEnglish: string,
      titleChinese: string,
      contentEnglish?: string | null,
      contentChinese?: string | null,
      _version: number,
      _deleted?: boolean | null,
      _lastChangedAt: number,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    nextToken?: string | null,
    startedAt?: number | null,
  } | null,
};

export type SyncQuestionsQueryVariables = {
  filter?: ModelQuestionFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
  lastSync?: number | null,
};

export type SyncQuestionsQuery = {
  syncQuestions?:  {
    __typename: "ModelQuestionConnection",
    items?:  Array< {
      __typename: "Question",
      id: string,
      questionType: QuestionType,
      titleEnglish: string,
      titleChinese: string,
      contentEnglish?: string | null,
      contentChinese?: string | null,
      _version: number,
      _deleted?: boolean | null,
      _lastChangedAt: number,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    nextToken?: string | null,
    startedAt?: number | null,
  } | null,
};

export type GetSubmissionQueryVariables = {
  id?: string,
};

export type GetSubmissionQuery = {
  getSubmission?:  {
    __typename: "Submission",
    id: string,
    submissionType: SubmissionType,
    submittedAt: string,
    temperature?: number | null,
    conditionsMet: boolean,
    signature: boolean,
    division?: Division | null,
    firstName: string,
    lastName: string,
    phone: string,
    parentID?: string | null,
    parentName?: string | null,
    parentPhone?: string | null,
    personID: string,
    familyID?: string | null,
    consultantType?: ConsultantType | null,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type ListSubmissionsQueryVariables = {
  filter?: ModelSubmissionFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListSubmissionsQuery = {
  listSubmissions?:  {
    __typename: "ModelSubmissionConnection",
    items?:  Array< {
      __typename: "Submission",
      id: string,
      submissionType: SubmissionType,
      submittedAt: string,
      temperature?: number | null,
      conditionsMet: boolean,
      signature: boolean,
      division?: Division | null,
      firstName: string,
      lastName: string,
      phone: string,
      parentID?: string | null,
      parentName?: string | null,
      parentPhone?: string | null,
      personID: string,
      familyID?: string | null,
      consultantType?: ConsultantType | null,
      _version: number,
      _deleted?: boolean | null,
      _lastChangedAt: number,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    nextToken?: string | null,
    startedAt?: number | null,
  } | null,
};

export type SyncSubmissionsQueryVariables = {
  filter?: ModelSubmissionFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
  lastSync?: number | null,
};

export type SyncSubmissionsQuery = {
  syncSubmissions?:  {
    __typename: "ModelSubmissionConnection",
    items?:  Array< {
      __typename: "Submission",
      id: string,
      submissionType: SubmissionType,
      submittedAt: string,
      temperature?: number | null,
      conditionsMet: boolean,
      signature: boolean,
      division?: Division | null,
      firstName: string,
      lastName: string,
      phone: string,
      parentID?: string | null,
      parentName?: string | null,
      parentPhone?: string | null,
      personID: string,
      familyID?: string | null,
      consultantType?: ConsultantType | null,
      _version: number,
      _deleted?: boolean | null,
      _lastChangedAt: number,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    nextToken?: string | null,
    startedAt?: number | null,
  } | null,
};

export type GetFamilyQueryVariables = {
  id?: string,
};

export type GetFamilyQuery = {
  getFamily?:  {
    __typename: "Family",
    id: string,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
    submissions?:  {
      __typename: "ModelSubmissionConnection",
      items?:  Array< {
        __typename: "Submission",
        id: string,
        submissionType: SubmissionType,
        submittedAt: string,
        temperature?: number | null,
        conditionsMet: boolean,
        signature: boolean,
        division?: Division | null,
        firstName: string,
        lastName: string,
        phone: string,
        parentID?: string | null,
        parentName?: string | null,
        parentPhone?: string | null,
        personID: string,
        familyID?: string | null,
        consultantType?: ConsultantType | null,
        _version: number,
        _deleted?: boolean | null,
        _lastChangedAt: number,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      nextToken?: string | null,
      startedAt?: number | null,
    } | null,
    members?:  {
      __typename: "ModelPersonConnection",
      items?:  Array< {
        __typename: "Person",
        id: string,
        firstName: string,
        lastName: string,
        phone?: string | null,
        email?: string | null,
        division?: Division | null,
        fatherPhone?: string | null,
        motherPhone?: string | null,
        fatherEmail?: string | null,
        motherEmail?: string | null,
        createdAt: string,
        updatedAt: string,
        submissionType: SubmissionType,
        isAuthenticatedUser: boolean,
        familyMemberType?: FamilyMemberType | null,
        familyID?: string | null,
        consultantType?: ConsultantType | null,
        governmentID?: string | null,
        _version: number,
        _deleted?: boolean | null,
        _lastChangedAt: number,
        submissions?:  {
          __typename: "ModelSubmissionConnection",
          items?:  Array< {
            __typename: "Submission",
            id: string,
            submissionType: SubmissionType,
            submittedAt: string,
            temperature?: number | null,
            conditionsMet: boolean,
            signature: boolean,
            division?: Division | null,
            firstName: string,
            lastName: string,
            phone: string,
            parentID?: string | null,
            parentName?: string | null,
            parentPhone?: string | null,
            personID: string,
            familyID?: string | null,
            consultantType?: ConsultantType | null,
            _version: number,
            _deleted?: boolean | null,
            _lastChangedAt: number,
            createdAt: string,
            updatedAt: string,
          } | null > | null,
          nextToken?: string | null,
          startedAt?: number | null,
        } | null,
      } | null > | null,
      nextToken?: string | null,
      startedAt?: number | null,
    } | null,
  } | null,
};

export type ListFamilysQueryVariables = {
  filter?: ModelFamilyFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListFamilysQuery = {
  listFamilys?:  {
    __typename: "ModelFamilyConnection",
    items?:  Array< {
      __typename: "Family",
      id: string,
      createdAt: string,
      updatedAt: string,
      _version: number,
      _deleted?: boolean | null,
      _lastChangedAt: number,
      submissions?:  {
        __typename: "ModelSubmissionConnection",
        items?:  Array< {
          __typename: "Submission",
          id: string,
          submissionType: SubmissionType,
          submittedAt: string,
          temperature?: number | null,
          conditionsMet: boolean,
          signature: boolean,
          division?: Division | null,
          firstName: string,
          lastName: string,
          phone: string,
          parentID?: string | null,
          parentName?: string | null,
          parentPhone?: string | null,
          personID: string,
          familyID?: string | null,
          consultantType?: ConsultantType | null,
          _version: number,
          _deleted?: boolean | null,
          _lastChangedAt: number,
          createdAt: string,
          updatedAt: string,
        } | null > | null,
        nextToken?: string | null,
        startedAt?: number | null,
      } | null,
      members?:  {
        __typename: "ModelPersonConnection",
        items?:  Array< {
          __typename: "Person",
          id: string,
          firstName: string,
          lastName: string,
          phone?: string | null,
          email?: string | null,
          division?: Division | null,
          fatherPhone?: string | null,
          motherPhone?: string | null,
          fatherEmail?: string | null,
          motherEmail?: string | null,
          createdAt: string,
          updatedAt: string,
          submissionType: SubmissionType,
          isAuthenticatedUser: boolean,
          familyMemberType?: FamilyMemberType | null,
          familyID?: string | null,
          consultantType?: ConsultantType | null,
          governmentID?: string | null,
          _version: number,
          _deleted?: boolean | null,
          _lastChangedAt: number,
          submissions?:  {
            __typename: "ModelSubmissionConnection",
            nextToken?: string | null,
            startedAt?: number | null,
          } | null,
        } | null > | null,
        nextToken?: string | null,
        startedAt?: number | null,
      } | null,
    } | null > | null,
    nextToken?: string | null,
    startedAt?: number | null,
  } | null,
};

export type SyncFamiliesQueryVariables = {
  filter?: ModelFamilyFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
  lastSync?: number | null,
};

export type SyncFamiliesQuery = {
  syncFamilies?:  {
    __typename: "ModelFamilyConnection",
    items?:  Array< {
      __typename: "Family",
      id: string,
      createdAt: string,
      updatedAt: string,
      _version: number,
      _deleted?: boolean | null,
      _lastChangedAt: number,
      submissions?:  {
        __typename: "ModelSubmissionConnection",
        items?:  Array< {
          __typename: "Submission",
          id: string,
          submissionType: SubmissionType,
          submittedAt: string,
          temperature?: number | null,
          conditionsMet: boolean,
          signature: boolean,
          division?: Division | null,
          firstName: string,
          lastName: string,
          phone: string,
          parentID?: string | null,
          parentName?: string | null,
          parentPhone?: string | null,
          personID: string,
          familyID?: string | null,
          consultantType?: ConsultantType | null,
          _version: number,
          _deleted?: boolean | null,
          _lastChangedAt: number,
          createdAt: string,
          updatedAt: string,
        } | null > | null,
        nextToken?: string | null,
        startedAt?: number | null,
      } | null,
      members?:  {
        __typename: "ModelPersonConnection",
        items?:  Array< {
          __typename: "Person",
          id: string,
          firstName: string,
          lastName: string,
          phone?: string | null,
          email?: string | null,
          division?: Division | null,
          fatherPhone?: string | null,
          motherPhone?: string | null,
          fatherEmail?: string | null,
          motherEmail?: string | null,
          createdAt: string,
          updatedAt: string,
          submissionType: SubmissionType,
          isAuthenticatedUser: boolean,
          familyMemberType?: FamilyMemberType | null,
          familyID?: string | null,
          consultantType?: ConsultantType | null,
          governmentID?: string | null,
          _version: number,
          _deleted?: boolean | null,
          _lastChangedAt: number,
          submissions?:  {
            __typename: "ModelSubmissionConnection",
            nextToken?: string | null,
            startedAt?: number | null,
          } | null,
        } | null > | null,
        nextToken?: string | null,
        startedAt?: number | null,
      } | null,
    } | null > | null,
    nextToken?: string | null,
    startedAt?: number | null,
  } | null,
};

export type GetPersonQueryVariables = {
  id?: string,
};

export type GetPersonQuery = {
  getPerson?:  {
    __typename: "Person",
    id: string,
    firstName: string,
    lastName: string,
    phone?: string | null,
    email?: string | null,
    division?: Division | null,
    fatherPhone?: string | null,
    motherPhone?: string | null,
    fatherEmail?: string | null,
    motherEmail?: string | null,
    createdAt: string,
    updatedAt: string,
    submissionType: SubmissionType,
    isAuthenticatedUser: boolean,
    familyMemberType?: FamilyMemberType | null,
    familyID?: string | null,
    consultantType?: ConsultantType | null,
    governmentID?: string | null,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
    submissions?:  {
      __typename: "ModelSubmissionConnection",
      items?:  Array< {
        __typename: "Submission",
        id: string,
        submissionType: SubmissionType,
        submittedAt: string,
        temperature?: number | null,
        conditionsMet: boolean,
        signature: boolean,
        division?: Division | null,
        firstName: string,
        lastName: string,
        phone: string,
        parentID?: string | null,
        parentName?: string | null,
        parentPhone?: string | null,
        personID: string,
        familyID?: string | null,
        consultantType?: ConsultantType | null,
        _version: number,
        _deleted?: boolean | null,
        _lastChangedAt: number,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      nextToken?: string | null,
      startedAt?: number | null,
    } | null,
  } | null,
};

export type ListPersonsQueryVariables = {
  filter?: ModelPersonFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListPersonsQuery = {
  listPersons?:  {
    __typename: "ModelPersonConnection",
    items?:  Array< {
      __typename: "Person",
      id: string,
      firstName: string,
      lastName: string,
      phone?: string | null,
      email?: string | null,
      division?: Division | null,
      fatherPhone?: string | null,
      motherPhone?: string | null,
      fatherEmail?: string | null,
      motherEmail?: string | null,
      createdAt: string,
      updatedAt: string,
      submissionType: SubmissionType,
      isAuthenticatedUser: boolean,
      familyMemberType?: FamilyMemberType | null,
      familyID?: string | null,
      consultantType?: ConsultantType | null,
      governmentID?: string | null,
      _version: number,
      _deleted?: boolean | null,
      _lastChangedAt: number,
      submissions?:  {
        __typename: "ModelSubmissionConnection",
        items?:  Array< {
          __typename: "Submission",
          id: string,
          submissionType: SubmissionType,
          submittedAt: string,
          temperature?: number | null,
          conditionsMet: boolean,
          signature: boolean,
          division?: Division | null,
          firstName: string,
          lastName: string,
          phone: string,
          parentID?: string | null,
          parentName?: string | null,
          parentPhone?: string | null,
          personID: string,
          familyID?: string | null,
          consultantType?: ConsultantType | null,
          _version: number,
          _deleted?: boolean | null,
          _lastChangedAt: number,
          createdAt: string,
          updatedAt: string,
        } | null > | null,
        nextToken?: string | null,
        startedAt?: number | null,
      } | null,
    } | null > | null,
    nextToken?: string | null,
    startedAt?: number | null,
  } | null,
};

export type SyncPeopleQueryVariables = {
  filter?: ModelPersonFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
  lastSync?: number | null,
};

export type SyncPeopleQuery = {
  syncPeople?:  {
    __typename: "ModelPersonConnection",
    items?:  Array< {
      __typename: "Person",
      id: string,
      firstName: string,
      lastName: string,
      phone?: string | null,
      email?: string | null,
      division?: Division | null,
      fatherPhone?: string | null,
      motherPhone?: string | null,
      fatherEmail?: string | null,
      motherEmail?: string | null,
      createdAt: string,
      updatedAt: string,
      submissionType: SubmissionType,
      isAuthenticatedUser: boolean,
      familyMemberType?: FamilyMemberType | null,
      familyID?: string | null,
      consultantType?: ConsultantType | null,
      governmentID?: string | null,
      _version: number,
      _deleted?: boolean | null,
      _lastChangedAt: number,
      submissions?:  {
        __typename: "ModelSubmissionConnection",
        items?:  Array< {
          __typename: "Submission",
          id: string,
          submissionType: SubmissionType,
          submittedAt: string,
          temperature?: number | null,
          conditionsMet: boolean,
          signature: boolean,
          division?: Division | null,
          firstName: string,
          lastName: string,
          phone: string,
          parentID?: string | null,
          parentName?: string | null,
          parentPhone?: string | null,
          personID: string,
          familyID?: string | null,
          consultantType?: ConsultantType | null,
          _version: number,
          _deleted?: boolean | null,
          _lastChangedAt: number,
          createdAt: string,
          updatedAt: string,
        } | null > | null,
        nextToken?: string | null,
        startedAt?: number | null,
      } | null,
    } | null > | null,
    nextToken?: string | null,
    startedAt?: number | null,
  } | null,
};

export type OnCreateQuestionSubscription = {
  onCreateQuestion?:  {
    __typename: "Question",
    id: string,
    questionType: QuestionType,
    titleEnglish: string,
    titleChinese: string,
    contentEnglish?: string | null,
    contentChinese?: string | null,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnUpdateQuestionSubscription = {
  onUpdateQuestion?:  {
    __typename: "Question",
    id: string,
    questionType: QuestionType,
    titleEnglish: string,
    titleChinese: string,
    contentEnglish?: string | null,
    contentChinese?: string | null,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnDeleteQuestionSubscription = {
  onDeleteQuestion?:  {
    __typename: "Question",
    id: string,
    questionType: QuestionType,
    titleEnglish: string,
    titleChinese: string,
    contentEnglish?: string | null,
    contentChinese?: string | null,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnCreateSubmissionSubscription = {
  onCreateSubmission?:  {
    __typename: "Submission",
    id: string,
    submissionType: SubmissionType,
    submittedAt: string,
    temperature?: number | null,
    conditionsMet: boolean,
    signature: boolean,
    division?: Division | null,
    firstName: string,
    lastName: string,
    phone: string,
    parentID?: string | null,
    parentName?: string | null,
    parentPhone?: string | null,
    personID: string,
    familyID?: string | null,
    consultantType?: ConsultantType | null,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnUpdateSubmissionSubscription = {
  onUpdateSubmission?:  {
    __typename: "Submission",
    id: string,
    submissionType: SubmissionType,
    submittedAt: string,
    temperature?: number | null,
    conditionsMet: boolean,
    signature: boolean,
    division?: Division | null,
    firstName: string,
    lastName: string,
    phone: string,
    parentID?: string | null,
    parentName?: string | null,
    parentPhone?: string | null,
    personID: string,
    familyID?: string | null,
    consultantType?: ConsultantType | null,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnDeleteSubmissionSubscription = {
  onDeleteSubmission?:  {
    __typename: "Submission",
    id: string,
    submissionType: SubmissionType,
    submittedAt: string,
    temperature?: number | null,
    conditionsMet: boolean,
    signature: boolean,
    division?: Division | null,
    firstName: string,
    lastName: string,
    phone: string,
    parentID?: string | null,
    parentName?: string | null,
    parentPhone?: string | null,
    personID: string,
    familyID?: string | null,
    consultantType?: ConsultantType | null,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnCreateFamilySubscription = {
  onCreateFamily?:  {
    __typename: "Family",
    id: string,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
    submissions?:  {
      __typename: "ModelSubmissionConnection",
      items?:  Array< {
        __typename: "Submission",
        id: string,
        submissionType: SubmissionType,
        submittedAt: string,
        temperature?: number | null,
        conditionsMet: boolean,
        signature: boolean,
        division?: Division | null,
        firstName: string,
        lastName: string,
        phone: string,
        parentID?: string | null,
        parentName?: string | null,
        parentPhone?: string | null,
        personID: string,
        familyID?: string | null,
        consultantType?: ConsultantType | null,
        _version: number,
        _deleted?: boolean | null,
        _lastChangedAt: number,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      nextToken?: string | null,
      startedAt?: number | null,
    } | null,
    members?:  {
      __typename: "ModelPersonConnection",
      items?:  Array< {
        __typename: "Person",
        id: string,
        firstName: string,
        lastName: string,
        phone?: string | null,
        email?: string | null,
        division?: Division | null,
        fatherPhone?: string | null,
        motherPhone?: string | null,
        fatherEmail?: string | null,
        motherEmail?: string | null,
        createdAt: string,
        updatedAt: string,
        submissionType: SubmissionType,
        isAuthenticatedUser: boolean,
        familyMemberType?: FamilyMemberType | null,
        familyID?: string | null,
        consultantType?: ConsultantType | null,
        governmentID?: string | null,
        _version: number,
        _deleted?: boolean | null,
        _lastChangedAt: number,
        submissions?:  {
          __typename: "ModelSubmissionConnection",
          items?:  Array< {
            __typename: "Submission",
            id: string,
            submissionType: SubmissionType,
            submittedAt: string,
            temperature?: number | null,
            conditionsMet: boolean,
            signature: boolean,
            division?: Division | null,
            firstName: string,
            lastName: string,
            phone: string,
            parentID?: string | null,
            parentName?: string | null,
            parentPhone?: string | null,
            personID: string,
            familyID?: string | null,
            consultantType?: ConsultantType | null,
            _version: number,
            _deleted?: boolean | null,
            _lastChangedAt: number,
            createdAt: string,
            updatedAt: string,
          } | null > | null,
          nextToken?: string | null,
          startedAt?: number | null,
        } | null,
      } | null > | null,
      nextToken?: string | null,
      startedAt?: number | null,
    } | null,
  } | null,
};

export type OnUpdateFamilySubscription = {
  onUpdateFamily?:  {
    __typename: "Family",
    id: string,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
    submissions?:  {
      __typename: "ModelSubmissionConnection",
      items?:  Array< {
        __typename: "Submission",
        id: string,
        submissionType: SubmissionType,
        submittedAt: string,
        temperature?: number | null,
        conditionsMet: boolean,
        signature: boolean,
        division?: Division | null,
        firstName: string,
        lastName: string,
        phone: string,
        parentID?: string | null,
        parentName?: string | null,
        parentPhone?: string | null,
        personID: string,
        familyID?: string | null,
        consultantType?: ConsultantType | null,
        _version: number,
        _deleted?: boolean | null,
        _lastChangedAt: number,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      nextToken?: string | null,
      startedAt?: number | null,
    } | null,
    members?:  {
      __typename: "ModelPersonConnection",
      items?:  Array< {
        __typename: "Person",
        id: string,
        firstName: string,
        lastName: string,
        phone?: string | null,
        email?: string | null,
        division?: Division | null,
        fatherPhone?: string | null,
        motherPhone?: string | null,
        fatherEmail?: string | null,
        motherEmail?: string | null,
        createdAt: string,
        updatedAt: string,
        submissionType: SubmissionType,
        isAuthenticatedUser: boolean,
        familyMemberType?: FamilyMemberType | null,
        familyID?: string | null,
        consultantType?: ConsultantType | null,
        governmentID?: string | null,
        _version: number,
        _deleted?: boolean | null,
        _lastChangedAt: number,
        submissions?:  {
          __typename: "ModelSubmissionConnection",
          items?:  Array< {
            __typename: "Submission",
            id: string,
            submissionType: SubmissionType,
            submittedAt: string,
            temperature?: number | null,
            conditionsMet: boolean,
            signature: boolean,
            division?: Division | null,
            firstName: string,
            lastName: string,
            phone: string,
            parentID?: string | null,
            parentName?: string | null,
            parentPhone?: string | null,
            personID: string,
            familyID?: string | null,
            consultantType?: ConsultantType | null,
            _version: number,
            _deleted?: boolean | null,
            _lastChangedAt: number,
            createdAt: string,
            updatedAt: string,
          } | null > | null,
          nextToken?: string | null,
          startedAt?: number | null,
        } | null,
      } | null > | null,
      nextToken?: string | null,
      startedAt?: number | null,
    } | null,
  } | null,
};

export type OnDeleteFamilySubscription = {
  onDeleteFamily?:  {
    __typename: "Family",
    id: string,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
    submissions?:  {
      __typename: "ModelSubmissionConnection",
      items?:  Array< {
        __typename: "Submission",
        id: string,
        submissionType: SubmissionType,
        submittedAt: string,
        temperature?: number | null,
        conditionsMet: boolean,
        signature: boolean,
        division?: Division | null,
        firstName: string,
        lastName: string,
        phone: string,
        parentID?: string | null,
        parentName?: string | null,
        parentPhone?: string | null,
        personID: string,
        familyID?: string | null,
        consultantType?: ConsultantType | null,
        _version: number,
        _deleted?: boolean | null,
        _lastChangedAt: number,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      nextToken?: string | null,
      startedAt?: number | null,
    } | null,
    members?:  {
      __typename: "ModelPersonConnection",
      items?:  Array< {
        __typename: "Person",
        id: string,
        firstName: string,
        lastName: string,
        phone?: string | null,
        email?: string | null,
        division?: Division | null,
        fatherPhone?: string | null,
        motherPhone?: string | null,
        fatherEmail?: string | null,
        motherEmail?: string | null,
        createdAt: string,
        updatedAt: string,
        submissionType: SubmissionType,
        isAuthenticatedUser: boolean,
        familyMemberType?: FamilyMemberType | null,
        familyID?: string | null,
        consultantType?: ConsultantType | null,
        governmentID?: string | null,
        _version: number,
        _deleted?: boolean | null,
        _lastChangedAt: number,
        submissions?:  {
          __typename: "ModelSubmissionConnection",
          items?:  Array< {
            __typename: "Submission",
            id: string,
            submissionType: SubmissionType,
            submittedAt: string,
            temperature?: number | null,
            conditionsMet: boolean,
            signature: boolean,
            division?: Division | null,
            firstName: string,
            lastName: string,
            phone: string,
            parentID?: string | null,
            parentName?: string | null,
            parentPhone?: string | null,
            personID: string,
            familyID?: string | null,
            consultantType?: ConsultantType | null,
            _version: number,
            _deleted?: boolean | null,
            _lastChangedAt: number,
            createdAt: string,
            updatedAt: string,
          } | null > | null,
          nextToken?: string | null,
          startedAt?: number | null,
        } | null,
      } | null > | null,
      nextToken?: string | null,
      startedAt?: number | null,
    } | null,
  } | null,
};

export type OnCreatePersonSubscription = {
  onCreatePerson?:  {
    __typename: "Person",
    id: string,
    firstName: string,
    lastName: string,
    phone?: string | null,
    email?: string | null,
    division?: Division | null,
    fatherPhone?: string | null,
    motherPhone?: string | null,
    fatherEmail?: string | null,
    motherEmail?: string | null,
    createdAt: string,
    updatedAt: string,
    submissionType: SubmissionType,
    isAuthenticatedUser: boolean,
    familyMemberType?: FamilyMemberType | null,
    familyID?: string | null,
    consultantType?: ConsultantType | null,
    governmentID?: string | null,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
    submissions?:  {
      __typename: "ModelSubmissionConnection",
      items?:  Array< {
        __typename: "Submission",
        id: string,
        submissionType: SubmissionType,
        submittedAt: string,
        temperature?: number | null,
        conditionsMet: boolean,
        signature: boolean,
        division?: Division | null,
        firstName: string,
        lastName: string,
        phone: string,
        parentID?: string | null,
        parentName?: string | null,
        parentPhone?: string | null,
        personID: string,
        familyID?: string | null,
        consultantType?: ConsultantType | null,
        _version: number,
        _deleted?: boolean | null,
        _lastChangedAt: number,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      nextToken?: string | null,
      startedAt?: number | null,
    } | null,
  } | null,
};

export type OnUpdatePersonSubscription = {
  onUpdatePerson?:  {
    __typename: "Person",
    id: string,
    firstName: string,
    lastName: string,
    phone?: string | null,
    email?: string | null,
    division?: Division | null,
    fatherPhone?: string | null,
    motherPhone?: string | null,
    fatherEmail?: string | null,
    motherEmail?: string | null,
    createdAt: string,
    updatedAt: string,
    submissionType: SubmissionType,
    isAuthenticatedUser: boolean,
    familyMemberType?: FamilyMemberType | null,
    familyID?: string | null,
    consultantType?: ConsultantType | null,
    governmentID?: string | null,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
    submissions?:  {
      __typename: "ModelSubmissionConnection",
      items?:  Array< {
        __typename: "Submission",
        id: string,
        submissionType: SubmissionType,
        submittedAt: string,
        temperature?: number | null,
        conditionsMet: boolean,
        signature: boolean,
        division?: Division | null,
        firstName: string,
        lastName: string,
        phone: string,
        parentID?: string | null,
        parentName?: string | null,
        parentPhone?: string | null,
        personID: string,
        familyID?: string | null,
        consultantType?: ConsultantType | null,
        _version: number,
        _deleted?: boolean | null,
        _lastChangedAt: number,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      nextToken?: string | null,
      startedAt?: number | null,
    } | null,
  } | null,
};

export type OnDeletePersonSubscription = {
  onDeletePerson?:  {
    __typename: "Person",
    id: string,
    firstName: string,
    lastName: string,
    phone?: string | null,
    email?: string | null,
    division?: Division | null,
    fatherPhone?: string | null,
    motherPhone?: string | null,
    fatherEmail?: string | null,
    motherEmail?: string | null,
    createdAt: string,
    updatedAt: string,
    submissionType: SubmissionType,
    isAuthenticatedUser: boolean,
    familyMemberType?: FamilyMemberType | null,
    familyID?: string | null,
    consultantType?: ConsultantType | null,
    governmentID?: string | null,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
    submissions?:  {
      __typename: "ModelSubmissionConnection",
      items?:  Array< {
        __typename: "Submission",
        id: string,
        submissionType: SubmissionType,
        submittedAt: string,
        temperature?: number | null,
        conditionsMet: boolean,
        signature: boolean,
        division?: Division | null,
        firstName: string,
        lastName: string,
        phone: string,
        parentID?: string | null,
        parentName?: string | null,
        parentPhone?: string | null,
        personID: string,
        familyID?: string | null,
        consultantType?: ConsultantType | null,
        _version: number,
        _deleted?: boolean | null,
        _lastChangedAt: number,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      nextToken?: string | null,
      startedAt?: number | null,
    } | null,
  } | null,
};
